- katas https://web.archive.org/web/20160701032652/https://codingdojo.org/cgi-bin/index.pl?KataCatalogue
  https://dojorena.io/manuals/43
  https://www.youtube.com/user/ltaravilse/videos
- https://dojorena.io/with/the-best-coding-challenge

- https://github.com/charlax/professional-programming
- https://github.com/cl2333/Grokking-the-Coding-Interview-Patterns-for-Coding-Questions
- https://github.com/codenjoyme/codenjoy
- https://github.com/ec24/tc-arg
- https://github.com/fogleman/AdventOfCode2021/
- https://github.com/jwasham/coding-interview-university
- https://github.com/matramos/elrejunte
- https://github.com/undefinedfceia/guardian-tortuga

- https://hackernoon.com/14-patterns-to-ace-any-coding-interview-question-c5bb3357f6ed
- https://malisper.me/an-algorithm-for-passing-programming-interviews/
- https://ourmachinery.com/post/data-structures-part-1-bulk-data/

- Web Hacking
  - https://overthewire.org/wargames/natas/
  - XSS
    - google XSS game https://xss-game.appspot.com/
    - PWN fucntion XSS Labs https://xss.pwnfunction.com/
    - port swigger XSS https://portswigger.net/web-security/cross-site-scripting
    - alert to win http://alf.nu/alert1?world=alert&level=alert0

- Admin Troubleshoting
  - https://sadservers.com/

- Terminal Skills
  - https://overthewire.org/wargames/bandit/

- Programming
  - https://hackattic.com/challenges
  - https://codecrafters.io/
  - Data
    - https://www.datawars.io/
  - Projects
    - https://github.com/codecrafters-io/build-your-own-x
    - https://github.com/AlgoryL/Projects-from-Scratch
    - https://github.com/practical-tutorials/project-based-learning
    - https://austinhenley.com/blog/challengingalgorithms.html
    - https://austinhenley.com/blog/morechallengingprojects.html
    - https://austinhenley.com/blog/challengingprojects.html
      https://news.ycombinator.com/item?id=21790779
  - Server
    - https://protohackers.com/
  - Distributed
    - https://fly.io/blog/gossip-glomers/
  - Problems
    - https://www.janestreet.com/puzzles/archive/
    - https://leetcode.com/
    - https://adventofcode.com/
    - https://cses.fi/problemset/
    - https://codeforces.com/
    - https://www.codechef.com/
    - https://www.hackerearth.com/
    - https://www.codingame.com/
    - https://www.hackerrank.com/
    - https://www.codewars.com/
    - https://projecteuler.net/
* Algos
** Graphs
|          | type | requirements             | O()      |
|----------+------+--------------------------+----------|
| Dijkstra | SSSP | no negative weight paths | E*log(V) |
|          |      |                          |          |
|----------+------+--------------------------+----------|
SSSP = Single Source Shortest Path
* Congruencies

- https://en.wikipedia.org/wiki/Modular_arithmetic
- problem https://www.codewars.com/kata/554f76dca89983cc400000bb/train/ocaml
- Books
  file:///home/sendai/disk/anybody/Steven%20Halim/Competitive%20Programming%203%20(4427)/Competitive%20Programming%203%20-%20Steven%20Halim.pdf#page=241
  file:///home/sendai/disk/anybody/David%20Esparza%20Alba/Algorithms%20For%20Competitive%20Programming%20(4592)/Algorithms%20For%20Competitive%20Programming%20-%20David%20Esparza%20Alba.pdf#page=311
  file:///home/sendai/disk/anybody/Skiena,%20Steven%20S_/Programming%20Challenges%20(4425)/Programming%20Challenges%20-%20Skiena,%20Steven%20S_.pdf#page=174

* Hackerank Bash
- Deletes all elements containing a or A
  ${countries/*[aA]*/}
- sort --stable
- readarray -t
- 2D Array - doesn't need $, can run operaations
  grid[col,row]='-'
  grid[col*row]='-'
- Slicing array
  ${countries[@]:START:HOWLONG}
- Concatenate 3 lines at the time ?????????????'''
  paste -d';' - - -
  paste -d';;\n'
- Sed I for insensitive eg: "s/FOO/BAR/gI" matches foo and FOo
- Sed & returns matched eg: "s/FOO/{&}/g" wraps in braces match
- forc loop, "rows" is a variable, not needing $
  for (( row = 0; row < rows; row++))
- += NEVER adds, always appends
* SadServers
** "Hong-Kong": can't write data into database.
$ sudo -u postgres psql -c "insert into persons(name) values ('jane smith');" -d dt
** "Karakorum": WTFIT – What The Fun Is This?
https://unix.stackexchange.com/questions/83862/how-to-chmod-without-usr-bin-chmod
- running chmod, when chmod does NOT haveexecution permisssions
/lib64/ld-linux.so /usr/bin/chmod +x wtfit
** TODO "Pokhara": SSH and other sshenanigans
- Test
  sudo -u client ssh client@localhost 'pwd'
- su /bin/bash: Resource temporarily unavailable
  https://serverfault.com/questions/1049908/centos7-su-bin-bash-resource-temporarily-unavailable
** TODO "Belo-Horizonte": A Java Enigma
        java.lang.UnsupportedClassVersionError: Sad has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0


00000000: cafe babe 0000 003d 003e 0a00 0200 0307  .......=.>......
00000010: 0004 0c00 0500 0601 0010 6a61 7661 2f6c  ..........java/l



admin@ip-172-31-43-201:~$ xxd HelloWorld.class | head
00000000: cafe babe 0000 003d 001d 0a00 0200 0307  .......=........
00000010: 0004 0c00 0500 0601 0010 6a61 7661 2f6c  ..........java/l
00000020: 616e 672f 4f62 6a65 6374 0100 063c 696e  ang/Object...<in
00000030: 6974 3e01 0003 2829 5609 0008 0009 0700  it>...()V.......
00000040: 0a0c 000b 000c 0100 106a 6176 612f 6c61  .........java/la
00000050: 6e67 2f53 7973 7465 6d01 0003 6f75 7401  ng/System...out.
00000060: 0015 4c6a 6176 612f 696f 2f50 7269 6e74  ..Ljava/io/Print
00000070: 5374 7265 616d 3b08 000e 0100 0d48 656c  Stream;......Hel
00000080: 6c6f 2c20 576f 726c 6421 0a00 1000 1107  lo, World!......
00000090: 0012 0c00 1300 1401 0013 6a61 7661 2f69  ..........java/i

admin@ip-172-31-43-201:~$ xxd Sad.class | head
00000000: cafe babe 0000 003d 003e 0a00 0200 0307  .......=.>......
00000010: 0004 0c00 0500 0601 0010 6a61 7661 2f6c  ..........java/l
00000020: 616e 672f 4f62 6a65 6374 0100 063c 696e  ang/Object...<in
00000030: 6974 3e01 0003 2829 5603 1900 0000 0800  it>...()V.......
00000040: 0901 0017 5665 7279 5361 646a 6176 612f  ....VerySadjava/
00000050: 6c61 6e67 2f4f 626a 6563 740a 000b 000c  lang/Object.....

printf '\x1d' | dd of=Sad.class bs=1 seek=6 conv=notrunc

* hackerinthewire
** bandit
- To get find to search for files in bytes use "c" suffix
  find . -size 100c
- ROT13 https://stackoverflow.com/questions/6441260/how-to-shift-each-letter-of-the-string-by-a-given-number-of-letters
  bandit11@bandit:~$ cat data.txt  | tr '[a-z]' '[n-za-m]' | tr '[A-Z]' '[N-ZA-M]'
  The password is JVNBBFSmZwKKOP0XbFXOoW8chDz5yVRv
- Revert an hexdump
  $ echo 01: 01 02 03 04 | xxd -r >output
- openssl s_client -connect 127.0.0.1:30001
- jN2kgmIXJ6fShzhT2avhotn4Zcka6tnt
  JQttfApK4SeyHwDlI9SXGR50qclOAil1
  awhqfNnAbc1naukrpqDYcF95h7HoMTrC
  VxCazJaVykI6W36BkBU0mJTCM8rR95XT ---------- 20?
  NvEJF7oVjkddltPSrdKEFOllh9V1IBcq ---------- 21
  WdDozAdTM2z9DiFEQ2mGlwngMfj4EZff ---------- 22
  QYw0Y2aiA672PsMmh9puTQuhoz8SyR2G ---------- 23
  VAfGXJ1PBSsPSnvsjI8p759leLZ9GGar ---------- 24
  p7TaowMYrmu23Ol8hiZh9UvD0O9hpx8d ---------- 25
  c7GvcKlw9mC7aUQaPx7nwFstuAIBw1o1 ---------- 26
  YnQpBuifNMas1hcUFk70ZmqkhUU2EuaS ---------- 27
  AVanL161y9rsbcJIsFHuw35rjaOM19nR ---------- 28
  tQKvmcwNYcFS6vmPHIUSI3ShmsrQZK8S ---------- 29
  xbhV3HpNGlTIdnjUrdAlPzc2L6y9EOnS ---------- 30
  OoffzGDlzhAlerFJ2cAiz1D41JW1Mhmt
  rmCBvG56y58BXzv98yZGdO7ATVL5dW8y
  odHo63fHiFqcWWJG9rLiLDtPm45KzUKy
  ------------------------
- TO avoid an "exit 0" on .bashrc
  ssh -l bandit18 -p 2220 bandit.labs.overthewire.org /bin/sh
- https://en.wikipedia.org/wiki/Setuid
- Can send something on a 1-time tcp server with
  echo "foo" | nc -l 8080
- Generating pincodes
  for i in {0..9999}; do printf "VAfGXJ1PBSsPSnvsjI8p759leLZ9GGar %04d\n" $i; done  > pins_space_zero.txt
- Escape from "more" with EDITOR, show few vertical lines
  EDITOR=/usr/bin/vim ssh -v -l bandit26 -i bandit26.privatekey -p 2220 bandit.labs.overthewire.org
  v
  :e /etc/bandit_pass/bandit26
  :set shell=/bin/bash
  :shell
- git show COMIT_ID:FILENAME
*** 30
- https://git-scm.com/book/en/v2/Git-Internals-Git-Objects
- git ls-remote --tags origin
#+begin_src
[~/wargames_bandit]$ git clone --branch secret ssh://bandit30-git@bandit.labs.overthewire.org:2220/home/bandit30-git/repo
Cloning into 'repo'...
                         _                     _ _ _
                        | |__   __ _ _ __   __| (_) |_
                        | '_ \ / _` | '_ \ / _` | | __|
                        | |_) | (_| | | | | (_| | | |_
                        |_.__/ \__,_|_| |_|\__,_|_|\__|


                      This is an OverTheWire game server.
            More information on http://www.overthewire.org/wargames

bandit30-git@bandit.labs.overthewire.org's password:
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
Receiving objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
error: object 831aac2e2341f009e40e46392a4f5dd318483019 is a blob, not a commit
[1]    2829766 segmentation fault (core dumped)  git clone --branch secret
#+end_src
- List objects
 #+begin_src
 $ git rev-list --objects --all | git cat-file --batch-check='%(objectname) $(objecttype) $(rest)' | column -t -s ' '        [master]
 59530d30d299ff2e3e9719c096ebf46a65cc1424  $(objecttype)  $(rest)
 831aac2e2341f009e40e46392a4f5dd318483019                 missing
 bd85592e905590f084b8df33363a46f9ac4aa708                 missing
 029ba421ef4c34205d52133f8da3d69bc1853777  README.md      missing
 #+end_src
- List objects (>2021)
 #+begin_src
 $ git cat-file --batch-all-objects --batch-check
 029ba421ef4c34205d52133f8da3d69bc1853777 blob 30
 59530d30d299ff2e3e9719c096ebf46a65cc1424 commit 194
 831aac2e2341f009e40e46392a4f5dd318483019 blob 33
 bd85592e905590f084b8df33363a46f9ac4aa708 tree 37
 #+end_src
- Cat deleted blob
  #+begin_src
 $ git cat-file -p 831aac
  OoffzGDlzhAlerFJ2cAiz1D41JW1Mhmt
  #+end_src
*** 31
~/.gitconfig
#+begin_src
[user]
        email = bandit31@overthewire.org
        name = bandit31
#+end_src
*** 32
pl2pm
>> /???/??2?? /???/??????_????/??????33
>> /???/??2?? /???/??????_????/??????32
Can't open /etc/bandit_pass/bandit32: Permission denied at /bin/pl2pm line 43.

col1
>> /???/???1 /???/??????_????/??????33
awk: fatal: cannot open file `/dev/vcs1' for reading: Permission denied

>> /???/?386
-sh: 1: /etc/profile.d/colon.sh: Syntax error: Bad function name
**** /3/1
>> /???/?
/bin/[: missing ‘]’
**** /3/2 CRASH?? memory dump???
**** /3/3
>> /???/???
E: Invalid operation /bin/awk
>> /???/??? ---
E: Command line option --- is not understood in combination with the other options
**** /3/4
>> /???/????
/bin/arch: extra operand ‘/bin/bash’
Try '/bin/arch --help' for more information.
**** /3/5
- sha512sum ????? same hash length and format
- sha512sum /bin/bzip2
e45085eefd2ce056377c4617cbdd5d05e96ba96ab4f31117f8db360138e70d837c0f357f4964be8b5b05cdf70baa3e8e0cabde69d13a08d1d43932856c11b898  /bin/bzip2
***** 3 c89 c99 c++ g++
7e4e1e9f19bc13eee35b2d10d5fdae21a46d777e5f5aa72bd115ba92891e68382bd1b160558f74e6d299fce82520a3f2483ec0a362e0b3d96900dbc7aef57a47  /bin/apt
202dcab4ccfdeab91de01458b91781ecb1e1ebee2dd0042227f3e30dce9daab3b2fea2cb4f7fb5777b7b76b528b41cbb2f82c0c7760dc0f508be43195e3c2efa  /bin/awk
c231c8bd55cc2c75c6f33e6bed6873156f21f444662fda52f3683e807626a8b3ff478d7a93e957d0fce24a85c2cf8545de2b77f0595544326cfa98af4cbaab1b  /bin/c++
3b0d95aa3f491c5dddc94779461e2f5ffd537cdb0015c8ab9390d7da6609e9c3763188d36e723f80119c4354061aaf9920de35137d43ebf04a6e7571461dcdbe  /bin/c89
c76258e4f6413fe9b5cc277931eb576bbb64ee79d9ef3ebe2699ee8fce2449c569d280f3e7f0d41f534413c502d654386a0e8d50e584182b7f11fb9fd68c540c  /bin/c99
2837ab96ae6c086637f291e3da66ebd43213492a846af2fce224c692f3cdb71cb84191eb97e14ec3e7ea3e42e7df021ff687ef79c5c372f7d699d3f5b6311bc4  /bin/cat
50b82f88627a6cef31e3d8a7060847a3221b6c764bc369ee42f97234b3cc9a66369b35ddb8dfcd5a781db502b028858d11dfb52f301655be5c1272b595bd52b7  /bin/cmp
3b2397f64da1e4ec5ef5681fee4123695f80f3825cd5f5a6aa16e0a580e95259f719d56effe0577e199302b6d72ea627ac2b9a07662c8b4fad6c5fe07a2defac  /bin/col
3d8086ee55032f6331247342ea0d99b6104fcbaf6e5faeebf126c8c9326892d72b4457e3daad26730aa4b043974ab31db5b0026c4d457315f47d7d426de9186c  /bin/cpp
184f55942db093cffafa2378afa509f7ecd7d7781f5c55fe8af4e9fff56d7a396d02670744f316a051d485529c05ef8bd9b507561f47eac16b8006eab821295d  /bin/cut
6283b3dcfbf7596221de38268c96c732b3728fc4050ec72bb2682401e9962603956ae5a7c87d0ee1862ac136fb70f8c2ee28b35576e4621c26f540acc63d3c4c  /bin/dig
62f425328e5e7a28624e2cb86c28ed3e19e1590cbe6dfaf42ebf8a44b76deb45f03a558c34debc63613eb7b5dd3a59a1b5f267619693591856247d9bf1ab20e5  /bin/dir
866b6b5f1ae68cb7ebe0820112272a1f1cdba226d0a32cd5599b0e9883d052de1587861795496b4b7c01900c9dbce3cff299e77695180bb0d8abd6a9b92abac8  /bin/dwp
97fd29d97045c7f014c04f736233a93460c64c1c2e8f9485807fde4719ba238c82e04530a73ec6ecd37e5bd5653f87a556e9b5593182502ab3f442ad93e4bb40  /bin/env
fbc56a998e2f3cc5bfb949717087bc61bd3497e2d456bbadac2083de99e51c4a078f86922a94f4fbd0b66dc211166f99527d3d956be1d4f8e9b8fb337e414c84  /bin/eqn
01f8c600ddd0a6ddaef9c6a3b08fee7fa63f24f46e86525355da5240eeab814a4efb889af2d49d4c81aaa6950b1c37fcdc6b6f50b7a2e53ef8bfbde5f9abbcef  /bin/fmt
3be3d1db62e71a078a95f83f31fb41378c54f21deb3de40baf17039be1c473be802a7ab7645a746a3061456cca7e843756f94249d78b34e07da3487dafbed0df  /bin/ftp
c231c8bd55cc2c75c6f33e6bed6873156f21f444662fda52f3683e807626a8b3ff478d7a93e957d0fce24a85c2cf8545de2b77f0595544326cfa98af4cbaab1b  /bin/g++
53d83dd2d9aef57b6f18fe4021d5786014529bea4a7643f8e9a60a5badb64dd3a6344978bf576f6c228fe2dbfb316440985f05dd7acc32d0b6ecf8b2119f79f6  /bin/gcc
908f1a983b7df7514f0f40553e844339cd9e86c81f6f3f87cb8f7d9c4b855799ab70d383b60ca480b7420f8e7dc48c9746ba72fc7b390eaf770c55f5750df987  /bin/gdb
928e753c0ac1e07e328d6e5e9236eb7576708a59d65d2b00d76383f62b44ef4f070b47066ae97c9ef57070540b312afd5f4f85cb6f5908f038b7bf1f4cb8a73c  /bin/gio
0f8a67826ddec42af7e34be56548e16edf41360a651f4abfc3ca773b22804b1e6339faf0a0c1a41fe4032b15b62352266f3825c8faaf8e6c4f265fa8b3e98808  /bin/git
85fce584153434a353c87f2aa68ed588a9b7ab4d880867d82bf1b04ddf68a7dfbea2f6cba262a210f9955d277d56e19a0534d5e1e952963df36e028b83034f38  /bin/gpg
1d3b09897ab7f93a2391bcce28285e88352df9f07ffb316a64c04da078e73b6aa16f07fcd508c0b22bd72297ed8b5a55c5045952fe161b3b1041aab0dc7493b1  /bin/lcf
8cf502604ff1d4759ccebbdbf9c5a864c797b2e3c9fa13b63d76f9b6b7e42c88960e0796585157541557ab31463ac3a4f82f1c22968e76f53ace45fa6ea0a441  /bin/ldd
d998bf352816f84bd08caceecf2ba890a5c63005d6d44b7eb9a7acdf7da90977b392ebd8b564cfbbbeff6577e32fc1663cc7e0b61f51cc3c82d1f9e630c9350c  /bin/man
db4334d169339990543aad43e3cdb2f2b3737fea6e0ecbf752b8b1854d631574044b7f857ac4740ef38e82c1aa1cce18a42690dc08ad573c9f59b1a1bef057aa  /bin/mtr
0d576449f947dffc8aac1a0a38470d28e4bdb649a035343d3af1bd3bf44ff432ed046eb300b7b33eb21f7b4f698d0765567dc2ea68f6022f1e9bf45e648a4e3d  /bin/pic
beb39a0e33d6624c63db777577a94ce4b76064fd5b7bf19c647f3f588c91a3d6ad8d668b8e1e6c226b32052e8af5ea91c3a36b90a3d907534ca904692c76adb2  /bin/pip
eafbb32591f429ff71939901ac312008ab542cad7f941c569fd4bfd2e2a92ca44101589abba6e08434045985425f419a96ba1ecd457402e49ae7e4621a794e8b  /bin/pro
fd9c071c3938213d4debb94cb56685ff46e17c4067231d8d302afb32d66f9637ea2330a0a802a6a886425e02b3531fc9c73032b7858b2de367ef90eeda918780  /bin/ptx
c0ea9401e948813a48b2b193d5a11ae4d414e7e6da0a23de22bf81e5aa3b2f9795f3a15db03f6ea2d7ba65c57f70fcdd8544771ce529e6a23222db9ea8290804  /bin/pwd
a15ead180c39e7aaf9583d7ceec701cd79a3de5f8693d44a7943779e6e5f75ffa95dbc978e6dd3abd789bc6fa155faa7e4c8acaffb4e33ad9da4109305338ea7  /bin/rcp
2c10a8a01a98a56e91fb62dd9268cac9420fcb493f78c7bd210f629e969a7843ffea26c367a1ef9004b05c684d4e5f9065261841699e1dff91d935457ec52401  /bin/rdx
7d1b44af6d44e64b8591c16805a1dd85bb06cfb2545d2b501c32a3a92083f3e543ff8d301ebc6a47f68259978d4f13ed4d220a989fadd693424405327a50c049  /bin/red
13d19aaaacc74c2948565b11997fce2f804cf7813ee485bc0a1700d205cb212bc767dc20e33c970fca91292bb5e73d8e265b0a2e84c6673d2773f29c8b628a8b  /bin/rev
98cdb71ad47b0449efb273acba1e1a372e9866175bd60f41805ae91f4db8e25a034cc4e5c5572b1dc2c90dcc3e9f4bffe84723320149d822b7ac73cf0926bcbe  /bin/rsh
06c7f4dd3b6b550e9c6758b2cc4e99a1933b2c000ab919990dab8bd0cd1c4c91afab8f66e7309b1dfc61ace692236d33935a5c9b9c5662d5c3cfbedc3dab46fb  /bin/sar
a15ead180c39e7aaf9583d7ceec701cd79a3de5f8693d44a7943779e6e5f75ffa95dbc978e6dd3abd789bc6fa155faa7e4c8acaffb4e33ad9da4109305338ea7  /bin/scp
ee9732f8d8a6a4a18f15a0bd01b51e9b7f73c8258fe1c1f3295e53faa83ef721664ee5fd92100b57a7c0072e7161a45bdfc3a91c1af60d98340c1e2aaa62d574  /bin/sed
6c00e44daa0e09a0542d566624b51bac1f00cd6aa24dcc514da498ab13ca1313bde1ff2e5f5d7aa22fb9edda564a68b7564f4ee9c6216783f1d271fa3c4aef7e  /bin/sem
ee4fd34956478141ff7a7cbbb77ceb6ce9613c6cfdfe42664ce9dcd683e4c0263175b7de5e0f396d7070afc860dd367bdc292c587ce16747b663eaa7f6b045d8  /bin/seq
88da1382543616ccf2577e1434abe9f0e61cea59c5c697b782317c2c2cf2ae4094c1fd1e00d0399e17dd2ed29ee183728b5f81077f92e234d0f1b6446e4381a1  /bin/sos
e7a00069d971fa21147d061031cffc656249eed793046b3b1cf9fd89528c340389e2af790fd0ee771d2f40e82c123e2fc4070eaebd2a8067c3dd624c0fedac86  /bin/sql
98cdb71ad47b0449efb273acba1e1a372e9866175bd60f41805ae91f4db8e25a034cc4e5c5572b1dc2c90dcc3e9f4bffe84723320149d822b7ac73cf0926bcbe  /bin/ssh
f5bfca5f0f1afe1bec08fb043188d71d12a1707c9216d46dcfb6fd9495f1f6b8dd5ba763ec06c54d3663e98852fd0ef52a5f8473fd61fee7259a306ef5920e1c  /bin/sum
c53ef0d61ad9101a8b87e33f9d6d65017b1909594900220d9e930a22d29b3e810b52e357c4dde17c3215070edef8bb7f44485269bc461a5e7005124aa0679443  /bin/tac
68ea3bfdaf82816f70c9998696aa26fb6d51d8c8da5f5729f0a807f936774c2e9dc66b1a34ca343847d93b0138d919b25b41b3da895210f626303002768c7d36  /bin/tar
daff5ec00f3cbd4ca414c930b1a2b0594199885ee2b685c17f3d795e282df91cb8484a0ec557d5aaec9342d14da1523168fda785b3ad00de40449d0016edb70f  /bin/tbl
7c1d29e305962daa60b2b94664419fa627caa803556f5c5a7db83541ce5275c94a46f569376d4cebd94badb660caea5ca3bee6efc429950eb165dafae90302ec  /bin/tee
d9bf1ab9d76c2bb04de34c31b21ba7dcd32b5a49e8845c5c65d0613d32409889f7c6884ddd87ece6d79ca4c9cf5f64b04919edc8a04b8bbbc838d12d20fe6fad  /bin/tic
5979a097e16049eb82bba0fe0eb9dd9957a96a6ace9e3e86a2d008869e952ce13c0bdf07dc49e5c243eb839e2972ee7c5eac5eb956ca66cd1be89d7890a527a6  /bin/toe
33e3e5c646f697d8157f160869f65d031e01112ce0e5f12555610f21d91e22b1f9c2d4abe8e65e3c4e22875fc115fddc2934c8086297f5bdde7cb3084859e303  /bin/top
452ce3d12c0fa2ff21a69b0fe1a42b0b8efd557aaba5e2bcc8ed43936316bd69ea7fd480b969c2f0b0c56855466ac1f118a001b3063c6b6d7679de4b4525702c  /bin/tty
685c2ea5135646a7ef7eef09c2708a4ece7bd15bdcb9fb44504fb9a73771eea7cc606a238e3d61f3d9b1c46f9361554d47813b2410a5fc4a1758f01f7f1f9679  /bin/ucf
48f04058ce6cc492fea183a602ac73a441f02d54a54ed2a20b9743442fc728414adbf56eab4f4e7ed6c16aa31994efc31fc6254a5619cbdb33409c07cb8456d3  /bin/vim
85faa001022e83d9b46479d3ce39020013cc1daedb0470638506ddb27934d498fc5da7b4e536615078723c7dcba68c209642807888e8ca9d511bb72f74ffbcb6  /bin/who
bbd6825aae35a4d0da86755022c123642296360bacc026244de504e6e5f1145769422302a92dba5950fd3be27f441ddaa47d05234aa65737c05c02870be74f4e  /bin/xxd
77bac81b1a749188ad5681868dff1b1a2c8a61208b0937c895ecb23c315eab5a22646c866540adfe7769e92249f517a60dd78fdd7362b0b3783db78115145fb8  /bin/yes
***** 2 NF
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/NF
a0f95298cbf0f6053a67fa86bafd660b13f2e4a4e7aaad1ec1ab55cc8c4a8830621e126209256d82bab3421c60eb52a07d5db2abb3df2192f7b4cc4704f20973  /bin/ar
adeb4c7e8de786ba08b131951c4065fd4e4b4c2a77b98c7fee4b0fe0421b524c4f6b335d52f23d6771bf7886740142cbac2657d561e6f7bffe8a565d1e80f5ec  /bin/as
b2d7e561b16ad4512549e63c824ff4487c297469bfdd37d254800a885b79992e4f5f359eee069b41eadee298d695637b9f4bf8cc7fdf0d2f143f9f622c43c5a7  /bin/bc
53d83dd2d9aef57b6f18fe4021d5786014529bea4a7643f8e9a60a5badb64dd3a6344978bf576f6c228fe2dbfb316440985f05dd7acc32d0b6ecf8b2119f79f6  /bin/cc
8b2092a5344a45dc0ad6a9b9383457f1c0fbbf796d3c70e5f98bf1d1fe11762276d667a3504cf92b4f1025132c2daaeed0b314f2c496dec4921704158adf43aa  /bin/cp
7c41d9a53396a44af4e4bd912e0b67628d17c4ab35fde5425a90523875ecb651f453e4c482537c50ac1dad310a542112c1bcb8028e4dc85106b405aaf75074c1  /bin/dd
f39a2ad9c26f5192c8937297945c5590822659845e03b291ecd5f446fec86986d8c9086391df1dc32144ba22709a50cb9b56a5cc54cf1791098de73dc183e0e6  /bin/df
d0084ee744b49f6d0cb0b5696ed75769375a6406b7fdbd5ac96e622edd52b7afb0c26ddd2774f5246a7c1c5867123fef3dbe955be0d06382f495bfc7d4470ddf  /bin/du
4c37de4b04bf7aa978706a701fd901fdf14dc9bfbc274aba9c28f0acd863e709c28a9cb500277ab56f263697b4a0691ca25717d238bd38daf28b50a2e36b5a7a  /bin/ed
48f04058ce6cc492fea183a602ac73a441f02d54a54ed2a20b9743442fc728414adbf56eab4f4e7ed6c16aa31994efc31fc6254a5619cbdb33409c07cb8456d3  /bin/ex
ebf8a222019276239e3eb4d24deff7f836a6a79073df47d6717111aadbd3b30e9e5109803a8edf4be904844662c11033e5f069478c498ead2e2f63dbeafbdf3b  /bin/hd
9997d0a9175802cf2613c73cc4ec77dc97c1280f8d1bd3d6121c5c5f06e2c22b7db1fca0e6ba8d3ef90bf5b838c49a02fcf4b07318891b29bbbc86da6f83e49d  /bin/id
ff81db879a4ba7d12563928e6690900f3f73309fd27b13b93a818ea9b1fbb9f39f465196238dfb65b5ee17803f41660de007b5d9641e4c39cfe592dd15962383  /bin/ip
2e9663c429b0b92658eefe19196b564b664467ec2ecc03c3a8db8595952c6831c227edf8f7ec85451d741af29979328595e6599dcfcc44d4cf3e51bab0b21f9d  /bin/jq
527b50a33421fff908952d72da33e2310c64a4228f64139650dd5630ba347042cb1518bc4c683565cb7459da41b7536b8f871d948f5a06b5849c9c7f87a20e2c  /bin/ld
a5d1258c0428336a30dc2443d865651fa0b12daa1a74450bac2d3dcc85fe87081d3cfa38b49fea41f40f8f048617b789afdb6c730474f753ccf73938703b6e85  /bin/ln
d813bdd2a2d0f64b1e3c3d4a12742c4a1b312684e0c09fa6bed85bf8c161c9aa41e54f9ba0937d3ea2c9e49511411bf1df6f66c74b752b872aeed1f2ebb8a7a4  /bin/ls
f16b6b7588efb82a3addb414333bafc365819eb77bb018748fd553331bb46766b4fa0761c77f6459d7b373d8fc48718c0bd578369d5598388efa067d4b4c7efa  /bin/mt
ec540bf4770455c245aaae6e5938a42dd45f4b8b18d2f5c0d967d3d58c4148ba7eefa66cda4baa86b022c058e7c50dc2ee198bb2f5361719f1b9f853bce1f928  /bin/mv
6dc143e3201e6ea0c6824e36f66e791564763b63b799fa2b0b654fe7e5569e20ceab0d32b23774435aec0768342999aeb243c4d6e79177d4a8910922fa3087fe  /bin/nc
502ffcc38349a23d8458a56a2fe041fbfa55ba6dcde888dd152eadc0af91d9f00a9012c6b25591ba662c3399862a0f4f8577518346a2a49003b20ef66b447e6f  /bin/nl
7908a81d5a4e693091340d13c646249a22af37e8cec199814565d997d773991099b86e948a053bf54af5e4622b8f812cc204e0ae0578238be4bdbfc578613a07  /bin/nm
7695347440bec77b48806e3fb58dc563be8bd73c15310ab9325dea522b1a1b46e7205a8b60e7b26bc3e4ae8f2e5ef1d6c03d911449a58feafb9bd40c0b19a6a0  /bin/od
d4e180516b618b5c38a37e9a216524d468a9a390a250f706324f7dcd0db8bae18f560ea2d6459aa433c43bea8f5f79319900147867cc5312fc69ccf7d843531d  /bin/pr
e3c432e6e6716ddc796cf662ead0e7c08bbb79df7870d54bbea475d3f2fc3f563d7819249354bcd8b560216c074b75d9ff1cb875dc6d634e410080afbb345b0e  /bin/ps
eb180ea3afbbe98b8c17964a9bb0a49143d7c739a187086aa7c3f067fbe0472211f82d89cc4bc8cadb6ac6c30642dd46d3913a3d7e62d98734ebde7969c97f9e  /bin/rm
ce3f8c247fbd4f2ff99edef9b383e8bfc9a1b8f6c9260a51b192bfd5f7bceb8e7265ffb96d2590335875f51a472d6027cc866eaee317c55e49fbf9a91cc84855  /bin/sg
f41c344c12080ad01e999bf314e925c593bd18074c9e574ea98fec5dbcf6cbe6cd83d1f05d4f2d35236d1a614ab8095a75136e7c956a014c9b5f8dcd4608763f  /bin/sh
a5e15b9f859aaf1747974853a47949201a74d7c7d8f2a0384824988bb97509f849a3441e0a3c1a2376d0577ae0e5ab5b46b0368e55911d17f1c2871c1e264a99  /bin/ss
01d6e55adb8db05aa30fd8b5a865373a201802aa4354e0d3312b100f9ed1d950c022d6e9c60e2177e4734d257f925b6588039ba4bfe1427e75dc56fb3e136d25  /bin/su
e12ec740a34aaed0aa680e93a40c8ac1bc75529e4f4887bef797561ae84b6e37f49f602c032c7acb3f8142412946559633172b696097290e7e9ccfd1bc0835b0  /bin/tr
eafbb32591f429ff71939901ac312008ab542cad7f941c569fd4bfd2e2a92ca44101589abba6e08434045985425f419a96ba1ecd457402e49ae7e4621a794e8b  /bin/ua
e27e41abb9c21a4c53f2383f5019652a80cab90335f2d7ab96a06259a129e798c6befe384998a3c972c5c278b6c48c44a9392851f72565a7288d15340f579467  /bin/ul
48f04058ce6cc492fea183a602ac73a441f02d54a54ed2a20b9743442fc728414adbf56eab4f4e7ed6c16aa31994efc31fc6254a5619cbdb33409c07cb8456d3  /bin/vi
b217583d7def156f022559f1f94b8d420200b6995d472a7fb4f6c19ac9b2f4d707380c5aa058a3e878227df2087834d859e792b79ccf46ed620e5e0db304be3a  /bin/wc
b9d16222f5c9b2de81056e67481fe6b7d2fd6fb372c701f83a6180f07929d89b0820a4ab2c02b86febd8981afeeede257226201bdb6ec2fdfbcb3b28db690894  /bin/xz
***** 4 col1-9 i386 h2ph h2xs pip3 pdb2 pdb3
5cc8e7fd9010a9a153b706f2c3276d04a7976931d98f17f4216de4d136a711826ebd13a471154bb762f03268c3173773fe1b1b5683a65d7a46a19c9ec114164c  /bin/arch
4d3782c0c3e9f91198f45093fc5baf5e062892f5097e4a5b278cfdd10f0beb3cf8288c5a45c9029c2d42cd30acce79ccb3ec3d94dec9279c69681508f591d4fb  /bin/bash
f0a6fb0343832b2dce785148fa423c67298b97d9b790591aa9c31593ccd8208409de23d5b2c951b777473be7108cd1d2f822d8495adb23dd64a0cafda0945c02  /bin/chfn
6786fa8e8fb8d5e88413596992367a70874ebc56610a8377c4255e59f766675c0f9e1ef0f00e6e56a0f12ba258056a8e5e6870448abf83f13ea5439fad984e97  /bin/chrt
e06da646edcfbf395a1f2d7945d2c10a218b88ee53db5658d275281b6727ba3a29dacb503078584d6d596f998e3b41fc0df3318749d8b4a1d0f110d73e487659  /bin/chsh
78c24d5850dbb4b5884dc1a2308938971ef8a26ba00ac760d4e8794632de3644fd208469d7a86aa0905c84cb9aef2282aed1c3c171d943564c34b3ca18bec86d  /bin/chvt
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col1
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col2
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col3
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col4
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col5
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col6
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col7
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col8
375d8a93bdb14232123f88b129dfb380497bdd14a0f2ec4dc5d95aa71c7086c334ff47b62f403518f6679eed860cc782b4a3310b3a72aea39a5d6cdfe29f3ab4  /bin/col9
1c56f4e2640bce5164b38bb30dbb59b05195f0cf1f378fb6608dc496f5d072b6584c84159ec2b35b92e3c5b63a81fade917ba826de3b14e5162892effc678258  /bin/comm
8b98e0f1430ebfdc00bd59a7b782337e646a73d49851878347b161b844de1b968eff0a003820d31878b4c24d4e5911f8e8c1a862c04978cf29b4e0530509d657  /bin/cpan
ef5b2daed53cc22203938d18e6a6218aa9de8d51e3234cefee9a4a759feeb048c3ea5f4033bb7a246f963f89596d3c0636d101313bffc2ed45b738b2497bee47  /bin/cpio
195771a565b36780a731f4cd8a2eebe0f799bd78723a1d524e83da5642d706382e09c027d495401810e088c3dcffac75ed23bdde44cc49fa35069f885646423c  /bin/curl
f41c344c12080ad01e999bf314e925c593bd18074c9e574ea98fec5dbcf6cbe6cd83d1f05d4f2d35236d1a614ab8095a75136e7c956a014c9b5f8dcd4608763f  /bin/dash
24048d306f80bdc4c537b561ae24d68c2fdadb2fe437133875001939f86f567eaebe6ad635e6c1cf84f3ec666383875571cc92bfd847e44db2cfe77fa27410d7  /bin/date
cd57151f8108a9889904eb587573c9cd4c597841f3547fb57a752f711f69d0afec21d77ec9afc63144e70f8ecf899801a66e150f9713798c5c3596438b13d438  /bin/delv
8f76c0f3bc62938d65b2e5d3611c04330b06c7e735ad0bd389319d159fc5770e5eeb2555fc649583c7129edeba541becd6ce8dcfd25d92ba078e895d5458dded  /bin/diff
a339f000fb35b25060ed61f36a387dbe43780826e2e4a67cbfe6342f1abbfd9a5ef5ca010d306d69e58ca749635fd455830406dc1a00c1b2ee895219d1e354b5  /bin/dpkg
18d0230f43932228ad4a92ada3c6ed85f002a9b403c0194abd8c9dded75a78048f6991e61b7ae15bec506d3ce7becbf6fc46a155f7c53b8874c4de856a4e976d  /bin/echo
64538727c2031c368d6c0150fe12068f1e503f7c720cd9dd7c8f428b3ace2e465ad04531359bb1853a2527379646a333996e2aa19573f6783a7862530c431e26  /bin/expr
18e3be14ddef6dac4d3f9be64a6070bab6ae3d25cefb25b5dbfe2882eb5928e111c21441fedbe651b829ce7cba55f043d664c2fbdd1f9fd9d531807f77245d49  /bin/file
74b977679c17d93ff9e58a2799d54c39e2adcf8354de57926adf8657765695bfdfb22b4a5e9776386135f25b1a64b92df7caeb5f9cf14c1a19c2e7f572666eea  /bin/find
3eb15bc90bb9712a79ac20840957678bb34449bc5a9874bca6109809977ea8b2a20d1c809d0e92c92b4b0bd6171cf5a9975758e1cb342e67cc37386fd5c465aa  /bin/fold
9a564420d7f360af91d3b07cb676029f6c8df04ba3edfb3d894a6941572c26d5584d5eb328f1facde6f5576191b2ef219995bb253cf1e5d1991dd8cf816ae300  /bin/free
202dcab4ccfdeab91de01458b91781ecb1e1ebee2dd0042227f3e30dce9daab3b2fea2cb4f7fb5777b7b76b528b41cbb2f82c0c7760dc0f508be43195e3c2efa  /bin/gawk
5c4e4b276e437661ac9702d56828f65451f62a4d0fc0fa042b73e28fddab1fc5ebe41d242c2a1a308e5bbe6b29730320ad95bc368c83db998ab2ee105d66e9d7  /bin/gcov
fbc56a998e2f3cc5bfb949717087bc61bd3497e2d456bbadac2083de99e51c4a078f86922a94f4fbd0b66dc211166f99527d3d956be1d4f8e9b8fb337e414c84  /bin/geqn
2103366997aeca807292aeb3bf159798e8ebc0288fdc134418dcbab249c8b23111c57e1e424b0fa4003ae7a47391dcc2badbb6749b1709786d9a897cc748a115  /bin/gold
0b05053ade6d33c554cb47a65623ad60c76bcb89daf7016f34f1b7cdf99e10ec899bcdc047e45406a64eb46efaf1376c22d96ad7722924f3e67bfd55fb3f1a0b  /bin/gpgv
0d576449f947dffc8aac1a0a38470d28e4bdb649a035343d3af1bd3bf44ff432ed046eb300b7b33eb21f7b4f698d0765567dc2ea68f6022f1e9bf45e648a4e3d  /bin/gpic
8ec04b99547a735a1634089e014103228bd10df73d7dfc8fea8528dc1cd61f8f00cd09eb8e67410ebae81c023575f61d69599971e3f28047315a2f48b5c1bc41  /bin/grep
83d06edce33b6c5dc2d165aef95ff362413902a1be1f61ed61662933591f215966249e2d5b011ef8ba8bfaa850b054d0252e67ffaf31d6b8fdfff15058130a41  /bin/grog
daff5ec00f3cbd4ca414c930b1a2b0594199885ee2b685c17f3d795e282df91cb8484a0ec557d5aaec9342d14da1523168fda785b3ad00de40449d0016edb70f  /bin/gtbl
989d066e928e827c0c9dfbd62a0e9264199e0bc88b7d4d76f24cb0e699ecb545e254e3c7d9c8e4e56e24df4619b4e07dfbaab804a2230a6102548d98923e2e37  /bin/gzip
a9ddbd8f5d9f476026d30be4f024f356695052b3146ac78ae724e635b9fad7dfd5d3c4e5d1519184138da01f69a4b9742c47dd8ae942fe2ada3ebd7eb8471e8d  /bin/h2ph
cbfb75b84b05428261da7c197b5f33bafc7053baadf2993313c444aa754ed52798f4985894115e2802a43f197e246e4df6051419ea3b47e5ef0df51938051730  /bin/h2xs
6d0667c8248cb92a456bd186557d97104782ed648640a30ffeaec8ce1424e6c3712dc854aa5225806764130f7d8bbbe6720e019dc765637ac91aa796de67683f  /bin/head
273323f610e4cac2b950c0dd10b88d2009b3c654b4aa0bf4eb817bdcbbd628b20240f2eaf68f47f8ec3e2124fab8e24c916d9d560a1f6d1069e7dbc770746ac1  /bin/host
95b3b38b48a7c87086401161961c6b15eb2aef16d0c6723c8bdb9d1cb75d90c3f996f94ff0e7193f1ae92a41d01501a1323a5fa67404fa12dbe3b64d07858921  /bin/htop
cedb75e70e30dfb50d3acae066cfb98515ce0b8dacc5f177937bdb143c684fdc855a548516449e738d49cf6caff8e49253942d820b81a7688b91a10936d8d661  /bin/i386
dc5547d70bada6e7d0dcdf48737f6feff8426d87b12b318fb8afa91cac81267f24c78a62ea0ad2b4acea76e77d39dfaee24e2cc342c9ac3a82cb45dbbaa8d70b  /bin/info
b5782e2098c9d339e8f4b58ca641727357b426c35144ab5f72101ccad28613e08f68f770e91726b5425882654a8085f641b2737677821ba1c8c20010793cd0f9  /bin/ipcs
90fc167728efa0fd85489207d6ae25ce4cb1c883353debfac2363b9d1fca0322a8d5d53c6e1d030d00d6a5e485a54d81f9819d8d888e723a846441ebff1ee37c  /bin/join
53b8d25aa15b18ca993cf307504e7e7f6f8f07fb9f05eb0b21cfc4064f361764ccca6a833c817a636ea7cbdb1684977a5e688634489946398f0a9e48a352797a  /bin/kill
65cfc9419072c6e73f8dfec22e3f63792b87ccc6222d01eacd65f3f69ab12ea17f2399a5008eceeae2d4b528884ebbba2d2191190f1d26e968b3e304c6a3c34c  /bin/kmod
5df58b450f274dd822e3ba57fefa615f98efbe2b0d2174496a228f53a4675e0a1abdb00f9d3d93ed034a8d30435b7231f8ab91fcad8a61dd443de9906037aedb  /bin/last
59cf6929f0f45d9a2e766322e56e9fd5b48dd40f7ef614e37aee3b9135fa4ce90cffb4e5d9bdc44fa27b63f380e50fa593924aa4b927077b42a94e1af1cbf152  /bin/less
b4f9a5033450d61b6ed8564bf9fdb7f52417f8d06d760b22eb0b52f6cda848fd5b5ed0f6e27433d41b353bb807eb5d87466b7063b36a790e3945d7f439d34147  /bin/link
29abe373e720bd1a9dac098a5993db87b0fe24c9bc1d3df4fa9c9932a5cf250c8814a34bd7cb722c1e6cf1c62a8e59e74e152d5e90eae267641c6245c02c619f  /bin/look
1278c67f3613fc69fdcf5f0d3c98844abf591f2e8ee32e3ae1c620e5f04f0117c0c77e2b576c4816d49aa8f8b7bc14a3526a42c970f390c753579995d7b0824f  /bin/lshw
f78b39a5bfb370d2f5af71f7f31a0e36f136df37df2a2b24550c59eea8f34b229215e5dabd739c369a8531a2ee4eaf9da98f7875505e7921b0cbbe4243a3b11e  /bin/lsns
f5cfaa9141e66031992958ea5938635072d29bc375f40b0576e85d80ddf8a60fa2aa9b1368752eee745300e78dc134102815b54dc629ac24cf5547e5e1cb1b96  /bin/lsof
b9d16222f5c9b2de81056e67481fe6b7d2fd6fb372c701f83a6180f07929d89b0820a4ab2c02b86febd8981afeeede257226201bdb6ec2fdfbcb3b28db690894  /bin/lzma
b30e6046c25c1571c71139e1f28d35c714974d1651cda9929df03b175abfef6a676043238397d6016ad68f9f7864b5a41bab1126585717a158c85c24baf9c113  /bin/make
8c1c9d1de0723e8e2c3742b83f7c2ec2c9b99b417ead3a809f8bd82ecd9903e3ecbcb78cb1b43a8cec1a9aeaf4ffbf00775ad367155f54ceb9931f129869237c  /bin/mawk
d91dbe7393fa2065811ddfe0c32a3993e49137c24a2b067a1a92c9644ba6c82c046e11579fd0cb73061834040197ddf7988aa3e9bc1efcad16edf7a4ab37a6b9  /bin/mdig
51e95f8635cb745e0c7b9a447e61d150a12b96f1aa93a874be8eec2e3e1448fed1bbf34e92b64d4c99b61a7763edcecc04c3a2265120476595e3fcb265b45f67  /bin/mesg
441c1d88dece28cab908cdb6a8edbf3c12ad3cbfda2a893c6743cff54d54ae04f20a7645840c98a82da8d8da5fdd2d5a66af6e9b3239286451b7353efe4c5b98  /bin/more
dd4ab9bfc99e0c62371df9b29450e4b4ad93d54d2d259629984279bb559a974b59ef10e05bd0288a700c79bed18dd6d7f5130e042c304dabb9f64ad5a35b794c  /bin/nano
ebe886f3991b36787f7e9f7a2ae597989829cd0319071690723fc4ddbd91d0a39fdeaeb22e791c25a9f524bfe7cbe901a258ef4e399b3b4d94ab4120e777a5a0  /bin/nasm
202dcab4ccfdeab91de01458b91781ecb1e1ebee2dd0042227f3e30dce9daab3b2fea2cb4f7fb5777b7b76b528b41cbb2f82c0c7760dc0f508be43195e3c2efa  /bin/nawk
1e4fccac2643c67ef4e02df4d16605f8cf1f328711f51e67eadc7447ee0730a55efd3dfe29daff081624f9a5823051f95bf5de50d351cef0aa77b14246b80de5  /bin/ncat
8d314adc434ee53b80105b027f78eb8ae7c7ba7a78d556957b06c0e57ea95045afa64705b650ba264923fe0cfa8f826384dc09c1498fb7795deae604fe1c2b24  /bin/neqn
5c9be9894398864388ad2db1eba62b5eb86df236c894f8d68bf12778552b752c660c923b7eefe083b7484323aa7bd63964364b535f8c726dda44607725f012cc  /bin/nice
ea6566c6d1993ab14cd77072e80de1c1d1139bfa0fbefbe27d9fa1ff92af1b7f4355221c2489a2fad9ae32f70bb0a72c3e8e36a79febbd96a900fd13da72646c  /bin/nmap
6d4bc57cff072cac739544b8744b2b03712b69809d1108829d22c60b60574ffc7b058198c1ecc46c2ee6cfc47f08e19a2908d9b51016a6aa0a18ce08a8fa7f16  /bin/pdb2
0678509b2df679dda825a566cd204c9c894cdb814f5b530077921f876d40759f9061bf1db059e84ee351b3de5863c6d3dd04fb73f81ad3f739b8892981090027  /bin/pdb3
3417763d36666dd7658691f3b9a2127a304fbb852d54e6dbca62db64e65ed54524f2460af0c0520e6624f0a2542e1dc6efc51ed5d5eaa375a77079be58aa0634  /bin/perl
dd4ab9bfc99e0c62371df9b29450e4b4ad93d54d2d259629984279bb559a974b59ef10e05bd0288a700c79bed18dd6d7f5130e042c304dabb9f64ad5a35b794c  /bin/pico
5122502a79802b5b6e8a33ab12540f6b1c783e896451c9548d7bb9fc11a9314a5f12bad599b0d164e17a4adf43685a74bb38658a1cbeb96d98685b5586da9e09  /bin/ping
beb39a0e33d6624c63db777577a94ce4b76064fd5b7bf19c647f3f588c91a3d6ad8d668b8e1e6c226b32052e8af5ea91c3a36b90a3d907534ca904692c76adb2  /bin/pip3
5ca4c735eb33d254da152d5fe6c887c30de5cab48a8a98111a405f6e5bc05089fe05bfcb44d2b1635d43098e6b13ac7ddaeac04469048b40c06b2efc9bd6f5d1  /bin/pldd
fb56076d9fb1d74d16b2c7997d978ab0398ae7911b43d13246f2a6828605501427dbea6a2e3dba184c663c4688c4b7d285258997dda2d5647a4ad01aa2fca976  /bin/pmap
c968e1630afac491fcafdc2f886b4f33a37a8be22e21629f975db116663ec8571d188a14adafbc3c13137d8fafe1ebc0256c4fc4cfefefe28b97573e3b56cab5  /bin/ptar
bb0f8f6cd5addcb307dacc500f9b9f42b4e278c5f71810ad4716750fec4a0d89bf2babcd1fd0ef50e80ec04c1597010372f7fda1e3eff701b2a1356e0ff9a759  /bin/pwdx
85881caa427b3255f481166ffa515f588d4a8aa2aaad84513123c8c1dc4155c8f99e9774a2cb2fea4a694a02ed57e30c9352704f06d93bda433faef9fbbfdb7f  /bin/rdma
48f04058ce6cc492fea183a602ac73a441f02d54a54ed2a20b9743442fc728414adbf56eab4f4e7ed6c16aa31994efc31fc6254a5619cbdb33409c07cb8456d3  /bin/rvim
b00c66cf2ca9b243d7cd8f02e12a21b13134924d56430899e8c55bcfc533faad20a43806625d615ce9f35b5238acfd249af0d49206e29af7c4532c511d187bcf  /bin/sadf
06e010933944e0917ba9c5329d180eb8e5c6bc1c22a83140dd8813459ab5505d6a71343fabed71ae3b48d4a1824825ef13e20f5e34b220a6f1fde171bd6d9bf9  /bin/sftp
aabfa9646da1a903654d4ba95a256a6983080222a6d0e29997e23ef4459cd881ee6340ee5fa882f6a7490c86e9182672e8e333defddb475a08cce3373ffa875a  /bin/shuf
e0b7212d7c18bafcb629b1bf62c684288a91aab9d809036389beac1f5443b094f4ac88dcc9549553f7cb008d82ce3c138825850b75f319b55132cd22ad60959a  /bin/size
6d64b5c3e2235b236e9fafa01061e5ac8ff5b21971ab21edfad0ac2998a77b609b4063ec5fe11a9af7c35e137d097fa61df3d4e81fda7525a5cae6c6ce5a673d  /bin/snap
b280df7b5231b2f6e5145b157ec2958fbeed1ea19e6d696b3cad54123077394269a5d26040cd9e95c2cb845b4941df895a8d27bf7b497a04199117fc2468c1f0  /bin/sort
2aabb2f107f791084494ee8b103ac339e239ffa3013f8eff8317944d7e9f3ad1a78af7254a69c41d2329fbbef6ab255457e83bb9605000d68be4c1d575ca6ad4  /bin/stat
f044aba0ed9ecd7e48211513b3eb6d09cb99b18b76d1935992625f8e9dfc411f8fc87fc4859f308f62bc8f1da313e016e37336f803ffc1f2554e7ce7f5e95fe6  /bin/stty
59717399ff494757f872cadc32060ce72a7692cc389638a55d7c974572cec98e866438e901cc3119590b9dd0540f2fc188485de9e38142c6c822b0e99890bebc  /bin/sudo
bd7dbea60f874545741cd17b0b326f3abe728495b5b7f028bfb9e84eb57a9c8101d70c602596be89daf1f5d7a089a8b77d36e97da32e8ef8b2618acf741641bb  /bin/sync
4a276f02d41bc0e16f6f23bdce993186332770bc359b972bfb78f2cf574f1820ca95144dda5d752b2babd62ef804a416fb43e7d8d1aad07ae1c74f724f4c01eb  /bin/tabs
f51b14bd05f3f51be0e3646edb366165f4e830bd4e63c0b22f65ecd55d8f16457159c337f78fa6827fafd302b8d1231d2bb25f915a957bc933d7a91fcaadd3d4  /bin/tail
9b2a60b9fdc574c0e41c1af68fa3407caddc36ac0749831a29f1d1db72f55922ff571eed5b6ea1b37e78bdf7009ef1719938c25d9b57ca3d9d8a49e33644af22  /bin/test
95f34ade2b86bf020337726b6ff842297451f568e6b340af1df87d21db7cb1ae6c2b8f525ded213ad2b76e03804bce51df1fdc02fba97a4469cbb284cb24445f  /bin/time
e2145b9e24ab9cb0daf36209c6136d69bf4664200194297c88c26ae873c73856ebc52664cca52cd3a5e9c1d6c5261b7faf516055a4037527ba2d3ebfdad08c12  /bin/tmux
2d98303a0df57e32ab5e6a74c7277d24718a8671c495c7a4ea2d187575c8170fcfdf412a48b20b8ab79505c48dd93023512389709ea25aa9ef71e3610f3329c0  /bin/tput
d6b438ad23f04db86d7cbc0d011b726762f7e6caae87c8c820f219acb27bb852b75fcd45c537ada1e53611916db4bde51a2136f9bb3817a1e74ffe2170b104f9  /bin/true
6e30d50be2cc88be7f0c9bc3097dab189fd03b6aaf29502a42ca03477a7744d130844847cdb8396e017a8e9787f545787d949394ea6d3081c7e6d0a5c9d1f245  /bin/tset
b2835acfd888089c496cc48ae56a249f6df3f714ddbb9b0e60a15fd4a1173d57337d83fe2663f390243c67798a51b91b8c85abc682a200f128bf403c6e9e4657  /bin/ucfq
0d96e3e7e58fe80f0da4ab5d9faa6739f5661e53c9f388476b6c3296cde452f6016715fbee0caffd7b99e9ee464ef57c91ffd6f4ff97ca1d5689386918ad2dea  /bin/ucfr
da514ac8ca9cceead780594fdf91acc6ae36f150a4675e9668f9a7dfdb387101bf929ef518273711799db992742ca49d89cb280584b0e533388e7e0ac3097da8  /bin/uniq
b9d16222f5c9b2de81056e67481fe6b7d2fd6fb372c701f83a6180f07929d89b0820a4ab2c02b86febd8981afeeede257226201bdb6ec2fdfbcb3b28db690894  /bin/unxz
8483c7c964f326d273bb8ddb7952d06bcb328010167b9e6265335f3f60351262e1a0f0e4009f5760120198822c9b991be09b87441f71b971f257baf5bcab85b1  /bin/vdir
48f04058ce6cc492fea183a602ac73a441f02d54a54ed2a20b9743442fc728414adbf56eab4f4e7ed6c16aa31994efc31fc6254a5619cbdb33409c07cb8456d3  /bin/view
9229199fe10cebc004e477a132d7d4736ea8643472071bcbe97bf0fdcf0a4e9f989852875e94699e58de4c5737148f34abdfa3bb035fb578ad339aee3032ee46  /bin/wall
4b8459c701c5ecaa5547c9b348ae90be46e693a7d18d588ea28f4b927afa27cecc9674520692d4e4462ab0b48e2ef78e0c55c795f38fb6e952b48b3a2dad8aed  /bin/wget
6cdcb466f94e66c823d8bbd3791e4fb526c3535a81f2563d476901daaf0553501edc997989e3720c343ec9ec1e8698a6431cb1f775789012af5a588b91af6ada  /bin/zcat
c0230ee7355604192ba8f461c013978d6d3a499223a305f0a7d27a1c2cf0ca11349ba5db1cd89e626c26ca1df1cf662b8ae2620ac8da728099472ad8ab148d5b  /bin/zcmp
7fbc8944019772a58801064b27ee5f4889bd4c10b82e91304d8fa21ef741e4e82267480bedd07784f394ee0c082b411b2df0064930cbe5424d55572e3b0ad700  /bin/znew
d95e17f54c5d6bf46fde2aa6c2feddde03d074a90206e4c2d3346306e4784610193d970b6f6b354b7fa3f766847ebc13ff077a4d986c7254e02bef168fb0b0ab  /bin/zstd
***** 5 bzip2 cftp3 diff3 ping4 ping6 pl2pm sg_dd
>> /???/?????
a8b0a98271eac43bb71c354fabe3d34bdfd334266fa0f57738ae765278199f0fd0773abbac8da27d2ea0e95a6580dc856c613bd51b0aebfe9afa9a9cf3d3cd3e  /bin/btrfs
c8a2b5c37fa41e675debb5bf1cf056854b039283308cea2fd31e9185debf250a9db29898dda885e71d7d66aea5e9e5e88c9e93b0865f0e6968e73d0693b9f8f6  /bin/byobu
778c9e55b9c1f6b1f410ea19211cc27401f284ddba2854fa447a0bafed5266de55d7597b4277fa976047eb6aa4f588e9863bef125b62414b11a170314d032dc3  /bin/bzcat
f7c3ce07bdbe108cef821ff44687d23e0181a79b63526a30697df10f73e92b1a7fe1cff7066accdeaa892e14cfa6a7788376396a61588e5b99cf91ef3bace401  /bin/bzcmp
a206886a66e0a09d3e34c3513c253ee6283c19c8112ece4b18aff4ac3d56e68dc062eac52a12900c5685e117d87b6d1ed3510fb3027e120d4f695f302da9b95a  /bin/bzexe
778c9e55b9c1f6b1f410ea19211cc27401f284ddba2854fa447a0bafed5266de55d7597b4277fa976047eb6aa4f588e9863bef125b62414b11a170314d032dc3  /bin/bzip2
570d0a4c226d87ebd02847df46a316e646595bf66268c1cd3e863915947d9428011abf170749a72d8d710410cb5a46ccfe8908f377699f29f004b53ede6f30bc  /bin/cftp3
b88ad6d5fad7e254e2e5e09fdc210c15f119eabed8a39339d97cdfc711a913e31885aad6439007be11f8f8ccb520dea3528f05e76bd6e2686f44246434a86c67  /bin/chage
cd42ec42ef77adfe1ae40f9d774b18d29bc5e0cf9d5bc59c6fe62bffff6db3a33f28f778314d5bcd1b8688473a8a590c695666a619e76c089a25622aff900fd3  /bin/chcon
061400e8a8a59bf24006cf2baea0b3c943fc99bbc704109e0ee196732e17d600cf1b1d7efe618b25bdf4f1a3749fc7c8ca73baafd86d37b06ab89d3b3cc98e0f  /bin/chgrp
1a405339c88996605b70493bc488aaf2e5075363a1b701081ffcb1b07a88c498ad6ec983edfadafdd5866fac7e83d4e47db4819b1942bb18669e5c89fad023cf  /bin/chmod
e4930337e4facdd58b4ee35d65f3222be576c7bbee570b4a3a8e16ef9d95bd7b4ec72d6fa11a4df25fb5284d54441350e3b454fd433a5a397a69785cd69daf42  /bin/choom
ff4a98bff3e8b204ce8fa2a8c77267154c53ad4eb576ae3351155408524643659342a385e5f07918ea2a989b5b1d3208714ebaa2ead6b05b0d233ba9b0b76ad6  /bin/chown
82219913a4446e5a8bfd9b265c9521dc2c4cb5e3259058e7fa5d8d0e293df77b8c491e81a1de6c1fffd449f5b3a741a4edc69d3bb7f4e08c09f1ffe98a298dec  /bin/cksum
ba50de679f1cf6f30fb2f3aa9d0e303c59d4305fbdb26ddf5a514fa2037151d3e859cc18b7955e8b8b946a93e65cf33fa7719f5b29855e119ad08594469b99d5  /bin/clear
2106f77d983c85ce1828e74f249d24ba2a6799d635e2a06f9c58f55c779978f7ac1e4f486c9fcab0dce4e5ed960154541a95a73ed1daa6988af7f9d112c30960  /bin/colrm
babb31993537976878b73b29a25319085185a6b9e1b9a75e9c8bf5aa051a6fd3aa2e2ec937e85d37c8ff5f40a93710c0c503c76de4e554f0cc1dcffa914ea7f6  /bin/ctail
8d884ed7878233aae1243447bbcdab09acb2ea9c5d2d6fd621e41c81889b156c2f143bea99746268beebacfe6feaa4bab6820c56d49496bd2e4171a26d1fac98  /bin/diff3
f170e06a901434e4fbd137cebb134aae515cbe409d7e7b2311698200c65cce255fb0c330597a917693c36935f2dc8f82814a6babffc632c654135200e98150f5  /bin/dmesg
db67859760f574c95f45ad2e5ad56f6f3bffeb2cf67683353a1f8f21e72f4de6be3c7046c7b71155bd35b9bdbaaa596c226bd7a4f607e2904b8b70aa379ac630  /bin/egrep
d5a85e93e0b4e9957f7b4cc02bf032fb0fb0b7c0795e95cc98379c470c2e4401869b889ee7f8ebacd2d0098192195904320c3b7930a3461d1a9e2193a7414bde  /bin/eject
ba467dd150b1b24f2eb46a8159405eae61ab2dd1c0fbf7fee036d019757e427ba2b0a3cd85615b242bbad19ac5adf0a584aaab35c9793aa530120abd7b666469  /bin/false
045bf8c5f62bada20eba10f16e4001e7160b6329be4d8f9882810bed3260175dd7cb0af115162b2e7e85bfa273f89630cf433fd994bf694efab3f1466d65dcbe  /bin/fgrep
68c2ac740d29760be9e7c74d1a7f42c6fe3b77915067bd21b30c2b2a20d8b91d6e30049714bc59f62247d6ebd03bc70dc309724f7160ec3432afb32aed3ce834  /bin/flock
cbe60271e70bc1759534fd2f2378a7f4a582c906fbfcc0c6eb781249db55f329a39e872822be30bbdec3474969bc1aa985481c65aed1cc93741bb08015f0194f  /bin/fuser
51ea9416d9bd803bd13c93f2d54709d647e660a00bf729bbe959332c4dc7deb9c4b7386c3c2dae8e5842f0c7ef242c4268388afb685a15fda70c750dac0f2987  /bin/gcore
ac4786f1ecf1b9594d98e6eee7bb1f4bff611d21c8f09d7e4f177117fde10de2758253534808ada1bf0b665a5ff18bcd982ed4ec1de25d1dd0806afa826f301f  /bin/gdbus
b30e6046c25c1571c71139e1f28d35c714974d1651cda9929df03b175abfef6a676043238397d6016ad68f9f7864b5a41bab1126585717a158c85c24baf9c113  /bin/gmake
952ad7606aaf717c9189042dfca7b11ae85012b61effab9483b4e909f53c206df1d7d6bdd35b42dfb51c8cda3e6bc93ef8ebd1373a39b1e201bbe60b5eec4e4b  /bin/gpgsm
e092eb28c0ba9d1682120badc66da867c23935006e548d7c7bcafd775f8ba0e2bf32276d0fe8041566a2da19d3bddb3dd1dd651e08b7c705a568668f81d18639  /bin/gprof
380cf0b5ccb602babdb0f0467e9ca9798112a63a6999690b538c6d52ec7ddcef930bde0bfd6e7c45e9e64924f133ea00a524509f94064febee1805a4a6fc2518  /bin/groff
d0ec7936071ef5cbe5ce84aac91799b81a6c687a42589be1e97b3c75a0e24ebf47e1a21957306eec73ad222c063f302a82100d6c53e245982c71be5255011307  /bin/grops
3915e8c8946f356a4d1ea7904c19b25e6ac5f13363843d143672a94dbf24189ae9f82f749446efe18045f7e054df732a775b3024d23d415432f9e99a4dd07045  /bin/gzexe
28751225aa9864dfd662dcef6c1b6f4e2650f566a43c4ddb2a0d8e2de2c1a3e473de5418acc8c58ae53cf274656526b592a9cacfc340840e857e08b7488124d8  /bin/iconv
ef3157e46803ee74542aadb5d24417a2f78f5cfdb09ed98d7db337f44f7ee876a9ac36e3734075b308ca4cb335e86259f9586359b6a452e734a6e55c2c29b2af  /bin/ipcmk
7ace0d029f997d8b75365ac4d79eaa944b478ee91a87a08382e67c109adaf2aed5a4068602fd298e1d38394acbeab91154001adeb593d06e71fe72368eac7d24  /bin/ipcrm
5df58b450f274dd822e3ba57fefa615f98efbe2b0d2174496a228f53a4675e0a1abdb00f9d3d93ed034a8d30435b7231f8ab91fcad8a61dd443de9906037aedb  /bin/lastb
20f728b84907aac5bfc9e4f3a77c54fa3e7c7b4d53d45625a41dba227302ae3e6834973acb3f7240589f5c2e53eff39037e8dd4b7985ff8cd9bd63f0f870464f  /bin/ldrdf
a4209a4a00513de33c75694346c259a2ae066ae670a7d042d66aaefc6c0c798229ca7bd6681253b001fbe4bd4513acbad180c7e23c6e26c7f17a061e1f92aa76  /bin/login
3466eb71714b5fedffd1ec8bea5add0d7ecc976cbccc60c01ecb5bdf1ed43809d5f0c006fdef1fcd023c895bd4b46d7e58b5d040f556558435de8e9032f83f4b  /bin/lsblk
cdbfa1d362763ed15a4b3d2f21bb7365e239f156d1a1d53b7f7f0b680414abda34d35945572a3ef3fd4891caf01d4221bcd51bb3d1ed020f237c40d29436dcde  /bin/lscpu
2a68d1f232b5273abd2092aede976cc24329d65129b9d64a39dd7634c432cfb17a95cde7767f6e008aa29ad960bb2541b9cd1874feee51543ffbc6d62edf95e4  /bin/lsipc
47946829ec2e4f2350341f6ace37dcb184885d1a950ce6638a811987cd460ff8b8d0b635ec16be221bbc68c0bbf1c53c6317a3b8bd0f0be3e376507a173f9dce  /bin/lsmem
65cfc9419072c6e73f8dfec22e3f63792b87ccc6222d01eacd65f3f69ab12ea17f2399a5008eceeae2d4b528884ebbba2d2191190f1d26e968b3e304c6a3c34c  /bin/lsmod
0793ddfddf5917c55f8000ba4c942793620a28882c71080b8278b246ec9ec7b6e886ba5b18eb69afe48358fb9258d6f65bec556d64eea504a5f984068bd58894  /bin/lspci
2fb4ac945d842a792341d8e7c038144376479fc2727e593fab121a5ec4f59358869e82be75bfb14cb9cc68713baa2f02a83a3487de202acab73c9b4d7b9bcc4e  /bin/lsusb
b9d16222f5c9b2de81056e67481fe6b7d2fd6fb372c701f83a6180f07929d89b0820a4ab2c02b86febd8981afeeede257226201bdb6ec2fdfbcb3b28db690894  /bin/lzcat
297a474f29f8271ea6a9feb1bb0ff0fa0480bf1df12065f8eeb66e28bf7ad33b109d4edf703ad1067979f250586ae0458b667dc181c3badcef90cbfc8e5abc63  /bin/lzcmp
9c4f94857ce62d51de30e36aacba20fd7835ad4baae7fe3aa428011893b6b06e588db0c4637975dc95eeec5086df580ab1a55e81e7237e3e4af21cf8c5f0e105  /bin/mandb
3ff1b8f930c21b404effe10db99505500f1cb43cad653ff78a08171e544d789aa2a5f3a1ceb61b3fcdf24f4d432e03f58fa5adccbfb3c7f9196b507bf57a7ead  /bin/mkdir
f758608e1d5a791d4612ced5fd17a76084ba1d30661116d10bf1cb252bfbdfe9fc6025ccd9b091035999504fbadb4f32bd848f55609d64eccb2ff034c4d0e020  /bin/mknod
45bcac87ddd4a7efdfe77d3e1fba800e111707108e2075a68091449cef4b41f24f3b733634aec8c9388e84d17bc8c1a693ce5abffaf7962ccf39787126c73bf7  /bin/mount
30e0b7855854cdb6effdfb2605c6df9ef76fd1772d9133bd53e5c624fcc0190d33cb1ed50d0ca20b7fddc545175fa7b9feffef928ca4b787789b01176ffb0cb6  /bin/namei
37a73f03bd7dfc482ec09d9cf09c06b15471acc31a625a1916ac558829bc925479598307975d856563893181a80e6f74c181ee6f0da398a38ee2bce0f533aee5  /bin/nohup
baa6811779ca1e30eee175146ca2adc74bdddba0990b7c245cf1bcb0d0e589b837d4af54f83a533e84894a57617b4b8c6a54a17c84259f58860ac89f512ac526  /bin/nping
833bd85753575939c3f4bbba7630b9480c4401cbdcac7f5eb6764f37830d48e9544f1f48b7ad400dde2fd2fa6f9156ae6d2685b3277f69a02b74698101523da9  /bin/nproc
e8cd0abdadac687d7df6ae24d3f663045a90996a46f44991ae2c19d2969acda34df29211eb7241401c20ff127eaea482bf4ea2a1a4b54683c78c121b247aa7e7  /bin/nroff
776caadefb8d280ced684f0fec0dc9cc78863faa26e6884bb54514fd6ecc8b54f4a7d7b191716a14be9465c7cc9d3c1303416a23a7883d3855d7a0bb9a153c02  /bin/nstat
59cf6929f0f45d9a2e766322e56e9fd5b48dd40f7ef614e37aee3b9135fa4ce90cffb4e5d9bdc44fa27b63f380e50fa593924aa4b927077b42a94e1af1cbf152  /bin/pager
d09bab4c1cc4bee518732c0f3eaef324b64121dcf41200ed0d09c2a494f17520ae081fc05659659e654b18dc58c8b40e2cca2f410db3cc619800fda808df3c64  /bin/partx
24fda0224c8febeef4caf4e1a59ced60eb62f9c7a6811c3b9ebec84c658f26a92fd1faa0e5add6db008f4c52f849f937d1316471c18634b8e3f3e0daeb03058f  /bin/paste
055995f242065c3aadddd15da2ddfe8e5158c8a948d2717ee1261dd51c9272c8b5b49197dd81575e8b1f551391bc7870b1c40b8984b4b79f6eb65c8f28c85e1c  /bin/patch
2449e0f6f4aa749ac3851df52aa7274ed16b419b23396faa6e3b10ec505de5f4dc13cde5afae014334265743ceea6025bcb3baaaba9ce149f250494a1eb28278  /bin/pbget
2449e0f6f4aa749ac3851df52aa7274ed16b419b23396faa6e3b10ec505de5f4dc13cde5afae014334265743ceea6025bcb3baaaba9ce149f250494a1eb28278  /bin/pbput
e4c45a986e1c9b51ec7c89f5a5e6e04a944e04fc42151699ca07fd8b8679e837ae5cb7ec7ab4a038529814d93bbe6d99b523f46908c0215660a434239aa7d347  /bin/pgrep
1d1d585b69d3b905ede544937b4b30de85456056ad713fc450385adf67f34999851c20d4490ebe9afe9d8ae4559130e9c568fb258bf2deea55c7fa067293156e  /bin/pidof
5122502a79802b5b6e8a33ab12540f6b1c783e896451c9548d7bb9fc11a9314a5f12bad599b0d164e17a4adf43685a74bb38658a1cbeb96d98685b5586da9e09  /bin/ping4
5122502a79802b5b6e8a33ab12540f6b1c783e896451c9548d7bb9fc11a9314a5f12bad599b0d164e17a4adf43685a74bb38658a1cbeb96d98685b5586da9e09  /bin/ping6
16234c2f9cad0f0d56931e835d9b6429857409e686c1ca8923833a9a8ec39b69d82d3d2f4a14738849745e47848b7a854c3d6f0aea236cf509924610f6b2657c  /bin/pinky
f9eb2f69604f4fb63f6da231207003e35f453d6e411bda1c2de62c9baf8329ee4722bf8351170ed36bbad57bb8b1274f3c8eb51aa69e555971f8905829ec7db5  /bin/pkcon
e4c45a986e1c9b51ec7c89f5a5e6e04a944e04fc42151699ca07fd8b8679e837ae5cb7ec7ab4a038529814d93bbe6d99b523f46908c0215660a434239aa7d347  /bin/pkill
3b842dced37aff0248b5574bab26b63d8012df339b9aec895b54d814c60ca180814283cbdbbaee8ef5f5a9a399d62aedcd3cbd7dd8ea2d9a0425d0fabc86f33f  /bin/pkmon
0ef940b58dd2d616bfaec9962128d8447004542128cf25d85964fa86e3be1cc09a83bd365608c3e4a588da509b7d196ad07e6f3c982585f20e94e17c51b8c8a0  /bin/pl2pm
6212ead509d5a4692872ff9ed8e52418b3878990a002be27954bac059531b206d9fd4fa3d92a3629128ab4434e99b5859fa082bdd552f4a30832929869b166d7  /bin/prove
dda528931929baa5ba00eab5d63319a19affa07386f548ddc0a100eef951e0b6f92e36281f55296f12c293d568b626a58f1042bbf86f661c141bbaa2342c4992  /bin/pslog
03d914c1bbd363df6de9da23426d496c4f83c25772b16e48958a0163f4b5c7f6953bf1403b52b244e92f4ca98ce5864825c54b8ba668145beecb3c42cc70bf06  /bin/pzstd
4d3782c0c3e9f91198f45093fc5baf5e062892f5097e4a5b278cfdd10f0beb3cf8288c5a45c9029c2d42cd30acce79ccb3ec3d94dec9279c69681508f591d4fb  /bin/rbash
6e30d50be2cc88be7f0c9bc3097dab189fd03b6aaf29502a42ca03477a7744d130844847cdb8396e017a8e9787f545787d949394ea6d3081c7e6d0a5c9d1f245  /bin/reset
488c682b25d7a6669493c2621536d6de2e647f9d71b139a9ea1623974e67171bbdad5fb9821b46428114d9a14703abd54766a0665af63e8f4a9ad29a6e4c2248  /bin/rgrep
3d49426f9d95dd9c270056e33ee478d7ccaeedb9e4dd125cc2a24fc8b68ff1ead2c4d99a90f35abc721e4a55650cb459ae34f659b7c48f9baef4f3c5609ace99  /bin/rmdir
dd4ab9bfc99e0c62371df9b29450e4b4ad93d54d2d259629984279bb559a974b59ef10e05bd0288a700c79bed18dd6d7f5130e042c304dabb9f64ad5a35b794c  /bin/rnano
ffba33227dcc8e71eb9f79ce7cd6b6334707f65ee4698b3a6936e4e8cd440a7909112b0bcf9d99f89c6e47c78c4a4d0687178d3cf51dc050951b4a4ca19c3ba8  /bin/rsync
48f04058ce6cc492fea183a602ac73a441f02d54a54ed2a20b9743442fc728414adbf56eab4f4e7ed6c16aa31994efc31fc6254a5619cbdb33409c07cb8456d3  /bin/rview
612a07d73d31d0af50f26f7ef3ecce8a7bf775f6ebf1a9a8b5385081acdcad61bfe0ca2404512b27aa665caec492b200aa316538bab496f5e0fdfa64a0ee5c52  /bin/sdiff
dc02fd9a9725bc301497468905a60deac8a49e41e1f357bbbdadb68360e395973b53b9b0adda975a8c2f8a1bdd6b41c9f7574e267a69faec7fcbf83df5c014ea  /bin/sg_dd
4b34f85aa34e939eae39b64f596b7785f548bcf32dac3e1368ec8d8db2bff5810138f0a6f308823f6b0cd1d8a205c8a79800d9a4dd67aa81d7296c7282d21417  /bin/shred
53b8d25aa15b18ca993cf307504e7e7f6f8f07fb9f05eb0b21cfc4064f361764ccca6a833c817a636ea7cbdb1684977a5e688634489946398f0a9e48a352797a  /bin/skill
f837e705e46dbe773bb308d834635b8e2681ddf9d69ef4c4862809304855913daf5cc276c1378dfbc90f4d0800cf42f7cd496cf6911a0e08c4ca838b4d38d135  /bin/sleep
53b8d25aa15b18ca993cf307504e7e7f6f8f07fb9f05eb0b21cfc4064f361764ccca6a833c817a636ea7cbdb1684977a5e688634489946398f0a9e48a352797a  /bin/snice
3d80b1c4d97a1a0461c1803cd2f47a3a8cf52f7afb1748afb8906067f0b4cf9d83dc16fb0caaead6cef90d83e773973e37b3354cf524eefc12570b873c3c3552  /bin/split
c54466cbfed81c81b01836d503590cab84ed26084a45d186beee2e9b7ad3b4aeb21123f04cbd5e7ce21da4bb3dda7889a85e42ea8cafd7e7344bf23be9019a27  /bin/sprof
e84b544042654132422885c74f3f61391119414c06f30bed83c2f7f4c107db75dd03a40e313dafed55827e8e433030cf769210d8902420724d3c63401d2c25af  /bin/strip
fca4c3dba7106edc32bcd43148584cf8c195bae10fd2664f7edfd52a7320e35fc4f80cf1904c918a9afb056f84904ecaa83595f9eaa00ffdb24a2d519bddf896  /bin/tclsh
106d0d5c3e8d01a70785fdeea39899ed609a1575b48c52d14f45463ba4edaef03574fc161b8a93e73b92abffc1790db4ea245d724fc1d6678c0ed81309bfc606  /bin/tload
3be3d1db62e71a078a95f83f31fb41378c54f21deb3de40baf17039be1c473be802a7ab7645a746a3061456cca7e843756f94249d78b34e07da3487dafbed0df  /bin/tnftp
519eac7c7e0aeb508af333abdb76325ac48b93471dc82eb38099f18e7bcdfa3715a230f86a308f66f8c75ae702468fea8557b8923d333b5b039a8b7c7ffb6f41  /bin/touch
2e4c4b8999be46b1c613ccf1305f5afbe5a3369de2cbdade8ed2dc25737cbb6ca8f1d8f28482983c00e09be9013c2c0a17437ab5e1eb4daebe4152536bc25f10  /bin/troff
8dac48161ca758d9fcd33317b25d2c764a3de0456454b5090478d762280833e8f72bc24f05fa998a0b13a90e04eb2d4588e5db128fef222094a10222f3121b8b  /bin/tsort
f3ac0d44bf5be8cb66afe64837ba15d8443f8db103c3c4704ead27d224d8e974ebc26ed1592ec2893215567bf51bff778761adc5878e7b70783bc674fe117ae9  /bin/uname
c426422a01279c3bad9c891481f069a12957f2848c3cb82a813e254700fd966d7c2d7216dfd7fb307261842244105117ee4868c0d688a5a77b425b76fcfa8cbf  /bin/users
ee0f985c8e53c946edba8d0f901908ca3629cd807e5ee0b8acbf3adb52072aaea12cba6364bafffe8d6533fe48042cb7c372c17d0c945abaed8cc6f0a15c63e6  /bin/vigpg
3629b2c7dbef04d03aae4de5a1c21e38cd14eb4496eaa984adabc1305e8caef2f16852ac9e2ecdd290e2b4320b714c787b18f9b5fbde6c36ba7c1aa39dc085d0  /bin/watch
d37f7be1c0ba00709a88183464ad34ed99dc6e58f48acb79c01a57b6ea8bf846d72b2b28a0254be6354036872f56dcaeba3c4485b87358fc3e470da466dd2942  /bin/wdctl
46f146157db003044c77ed3e3f7a766e5d9ca9c5c1afcdbd6d50844c0a1788878318e0795a3145ea5e838771751add0e3a7ea75b161d453aba826b2caec0644c  /bin/which
fbd7242acf0b257985f0ec560bd51ad447fd7ea80077c404405ffec34903861ff798774ce3a9a7976fe344839b9ebe36a7b1a86a8a5fcf0e216be25acba3a334  /bin/write
b7e72158bd84bbb75d483d233586c1ee28797d91111e5b58bb5c9fec4575605aa764d9412c858478ddeec84f3c79186b5fb7acad90c755acf97ef1e28a0237c3  /bin/xargs
71547454a1b5e92e6f50aeacc3fc9ee24e5a2aa227981f347a59481e88b272cafd894c1113ab0bd565b471b30268df142ae3666310297f12cd86586c349deb43  /bin/xauth
b9d16222f5c9b2de81056e67481fe6b7d2fd6fb372c701f83a6180f07929d89b0820a4ab2c02b86febd8981afeeede257226201bdb6ec2fdfbcb3b28db690894  /bin/xzcat
297a474f29f8271ea6a9feb1bb0ff0fa0480bf1df12065f8eeb66e28bf7ad33b109d4edf703ad1067979f250586ae0458b667dc181c3badcef90cbfc8e5abc63  /bin/xzcmp
8d69e22ca15903d37bd9cefdd87b44c4e9d7a3c50f978c7de853ef0014a6774263a5201d40aa89fbe9851a4da2004fc336f2371a8117a92443195b890ad8f637  /bin/zdiff
9a788870443493075b4fa872684a6c3fd29e7a86fe02762ec173b53437110850786ee413de0ea95f52f5ce59df70e35adae21a99f57dda0e2391e5b781144634  /bin/zdump
26eb23ce16881a71185ea85702368adc77aa71af945bd50e20241049ba9a953c3094da445e2e27ac8103f01493061f0c5bc9f86ff8a7763aa245c77c545fbd4d  /bin/zgrep
11e3e6e5ec20478a49e0588a95b6b483c92dbc9d13140578ce580b312510a0d239c57e64ef35fe50db4da044072324b21e3c9dae4b64436e1d1685a467a3b6cd  /bin/zless
85c0595c111a55926c75ac3c8837e7367872fe1f31227c4900fa56c86fa010b30f73c0f16f7c62348ad2c476d1ea07629cea5937c6a288cf53b922405388105d  /bin/zmore
/bin/b2sum: /dev/block: Is a directory
/bin/b2sum: /dev/hwrng: Permission denied
/bin/b2sum: /dev/input: Is a directory
/bin/b2sum: /dev/loop0: Permission denied
/bin/b2sum: /dev/loop1: Permission denied
/bin/b2sum: /dev/loop2: Permission denied
/bin/b2sum: /dev/loop3: Permission denied
/bin/b2sum: /dev/loop4: Permission denied
/bin/b2sum: /dev/loop5: Permission denied
/bin/b2sum: /dev/loop6: Permission denied
/bin/b2sum: /dev/loop7: Permission denied
/bin/b2sum: /dev/ng0n1: Permission denied
/bin/b2sum: /dev/nvme0: Permission denied
/bin/b2sum: /dev/nvram: Permission denied
/bin/b2sum: /dev/psaux: Permission denied
/bin/b2sum: /dev/stdin: Permission denied
/bin/b2sum: /dev/tty10: Permission denied
/bin/b2sum: /dev/tty11: Permission denied
/bin/b2sum: /dev/tty12: Permission denied
/bin/b2sum: /dev/tty13: Permission denied
/bin/b2sum: /dev/tty14: Permission denied
/bin/b2sum: /dev/tty15: Permission denied
/bin/b2sum: /dev/tty16: Permission denied
/bin/b2sum: /dev/tty17: Permission denied
/bin/b2sum: /dev/tty18: Permission denied
/bin/b2sum: /dev/tty19: Permission denied
/bin/b2sum: /dev/tty20: Permission denied
/bin/b2sum: /dev/tty21: Permission denied
/bin/b2sum: /dev/tty22: Permission denied
/bin/b2sum: /dev/tty23: Permission denied
/bin/b2sum: /dev/tty24: Permission denied
/bin/b2sum: /dev/tty25: Permission denied
/bin/b2sum: /dev/tty26: Permission denied
/bin/b2sum: /dev/tty27: Permission denied
/bin/b2sum: /dev/tty28: Permission denied
/bin/b2sum: /dev/tty29: Permission denied
/bin/b2sum: /dev/tty30: Permission denied
/bin/b2sum: /dev/tty31: Permission denied
/bin/b2sum: /dev/tty32: Permission denied
/bin/b2sum: /dev/tty33: Permission denied
/bin/b2sum: /dev/tty34: Permission denied
/bin/b2sum: /dev/tty35: Permission denied
/bin/b2sum: /dev/tty36: Permission denied
/bin/b2sum: /dev/tty37: Permission denied
/bin/b2sum: /dev/tty38: Permission denied
/bin/b2sum: /dev/tty39: Permission denied
/bin/b2sum: /dev/tty40: Permission denied
/bin/b2sum: /dev/tty41: Permission denied
/bin/b2sum: /dev/tty42: Permission denied
/bin/b2sum: /dev/tty43: Permission denied
/bin/b2sum: /dev/tty44: Permission denied
/bin/b2sum: /dev/tty45: Permission denied
/bin/b2sum: /dev/tty46: Permission denied
/bin/b2sum: /dev/tty47: Permission denied
/bin/b2sum: /dev/tty48: Permission denied
/bin/b2sum: /dev/tty49: Permission denied
/bin/b2sum: /dev/tty50: Permission denied
/bin/b2sum: /dev/tty51: Permission denied
/bin/b2sum: /dev/tty52: Permission denied
/bin/b2sum: /dev/tty53: Permission denied
/bin/b2sum: /dev/tty54: Permission denied
/bin/b2sum: /dev/tty55: Permission denied
/bin/b2sum: /dev/tty56: Permission denied
/bin/b2sum: /dev/tty57: Permission denied
/bin/b2sum: /dev/tty58: Permission denied
/bin/b2sum: /dev/tty59: Permission denied
/bin/b2sum: /dev/tty60: Permission denied
/bin/b2sum: /dev/tty61: Permission denied
/bin/b2sum: /dev/tty62: Permission denied
/bin/b2sum: /dev/tty63: Permission denied
/bin/b2sum: /dev/ttyS0: Permission denied
/bin/b2sum: /dev/ttyS1: Permission denied
/bin/b2sum: /dev/ttyS2: Permission denied
/bin/b2sum: /dev/ttyS3: Permission denied
/bin/b2sum: /dev/vcsa1: Permission denied
/bin/b2sum: /dev/vcsa2: Permission denied
/bin/b2sum: /dev/vcsa3: Permission denied
/bin/b2sum: /dev/vcsa4: Permission denied
/bin/b2sum: /dev/vcsa5: Permission denied
/bin/b2sum: /dev/vcsa6: Permission denied
/bin/b2sum: /dev/vcsu1: Permission denied
/bin/b2sum: /dev/vcsu2: Permission denied
/bin/b2sum: /dev/vcsu3: Permission denied
/bin/b2sum: /dev/vcsu4: Permission denied
/bin/b2sum: /dev/vcsu5: Permission denied
/bin/b2sum: /dev/vcsu6: Permission denied
/bin/b2sum: /etc/byobu: Is a directory
/bin/b2sum: /etc/cloud: Is a directory
/bin/b2sum: /etc/emacs: Is a directory
/bin/b2sum: /etc/fonts: Is a directory
4ef64e15e2369121336ad6e7b7b4247fa5fdf143cd8a65b320a1a97dbe84db9ba1ef59357174e7789a77cb23980d3654eb2bdda02f0bfc109226249d8efd36ea  /etc/fstab
/bin/b2sum: /etc/groff: Is a directory
8095a39f238e841c7d9100c6286f6ddde2044be716201df9ffbe550ef73d32b0a1cfdf87731148c6b845c991489ef2dbc619020fd2a63f3da52af3395b0a79c1  /etc/group
e9b5eeee041ca00319d03378d3302909f58cfbe8c3e44e654d26c695e390f186f2f4374aec15254c5355f66b7194de89fbea92125de5a79a4632f9f65d55a3f4  /etc/hosts
/bin/b2sum: /etc/iscsi: Is a directory
efc774aff14d0af588605ef87d4cf48a73244c7bea02d80ff6b2e29290b0527b70dde964dd4def91e81b15f00634bc84a6723a3512fbaf17f33cea26e9e33341  /etc/issue
474c2e9ef56f89c7747b835c18c3c43eb51b1a8478042ac4bb5d10197a108f8cb855e07dd69de71b5a9c0c8dbb7451385960f9d0d404b5cbd8c8ac046f9a270b  /etc/legal
2e4c726e7c2d71468600fbf316b8d2d04bd062ed3ad5c83e7d37ee47bc9d9a245a1c26865867d53f7b18b8ef1fabb0c7c71a946f2201570ae6232f47d4ac7ab8  /etc/magic
/bin/b2sum: /etc/mdadm: Is a directory
/bin/b2sum: /etc/pam.d: Is a directory
/bin/b2sum: /etc/rc0.d: Is a directory
/bin/b2sum: /etc/rc1.d: Is a directory
/bin/b2sum: /etc/rc2.d: Is a directory
/bin/b2sum: /etc/rc3.d: Is a directory
/bin/b2sum: /etc/rc4.d: Is a directory
/bin/b2sum: /etc/rc5.d: Is a directory
/bin/b2sum: /etc/rc6.d: Is a directory
/bin/b2sum: /etc/rcS.d: Is a directory
e89320ee7a0b9c5acd1287d08914c72eeb5ce0333611cfaa696d29b8337c27cd0d9050de032a6f4c6f24d7a556ff5f044dd04b8d9c90ce84477c2434206d119d  /etc/vtrgb
/bin/b2sum: /lib/byobu: Is a directory
/bin/b2sum: /lib/debug: Is a directory
/bin/b2sum: /lib/gnupg: Is a directory
/bin/b2sum: /lib/groff: Is a directory
/bin/b2sum: /lib/klibc: Is a directory
/bin/b2sum: /lib/linux: Is a directory
/bin/b2sum: /lib/pam.d: Is a directory
/bin/b2sum: /lib/sasl2: Is a directory
/bin/b2sum: /lib/snapd: Is a directory
/bin/b2sum: /run/blkid: Is a directory
/bin/b2sum: /run/mount: Is a directory
/bin/b2sum: /run/netns: Is a directory
/bin/b2sum: /run/snapd: Is a directory
/bin/b2sum: /run/uuidd: Is a directory
/bin/b2sum: /sys/block: Is a directory
/bin/b2sum: /sys/class: Is a directory
/bin/b2sum: /sys/power: Is a directory
/bin/b2sum: /usr/games: Is a directory
/bin/b2sum: /usr/lib32: Is a directory
/bin/b2sum: /usr/lib64: Is a directory
/bin/b2sum: /usr/local: Is a directory
/bin/b2sum: /usr/share: Is a directory
/bin/b2sum: /var/cache: Is a directory
/bin/b2sum: /var/crash: Permission denied
/bin/b2sum: /var/local: Is a directory
/bin/b2sum: /var/spool: Is a directory
**** /3/6 - "/bin/base32"
>> /???/??????
/bin/base32: extra operand ‘/bin/basenc’
Try '/bin/base32 --help' for more information.

>> /???/????32                /???/??????_????/??????32
   /bin/base32 SOMEDIRECTORY? /etc/bandit_pass/bandit32
/bin/base32: extra operand ‘/etc/bandit_pass/bandit32’
Try '/bin/base32 --help' for more information.

>> /???/????32
/bin/base32: read error: Is a directory
**** /3/7 - "/bin/addpart"
>> /???/???????
addpart: not enough arguments
Try 'addpart --help' for more information.
**** /3/8 - "/bin/2to3-2.7"
>> /???/????????
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
Traceback (most recent call last):
  File "/bin/2to3-2.7", line 5, in <module>
    sys.exit(main("lib2to3.fixes"))
  File "/usr/lib/python2.7/lib2to3/main.py", line 260, in main
    options.processes)
  File "/usr/lib/python2.7/lib2to3/refactor.py", line 706, in refactor
    items, write, doctests_only)
  File "/usr/lib/python2.7/lib2to3/refactor.py", line 301, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib/python2.7/lib2to3/refactor.py", line 747, in refactor_file
    *args, **kwargs)
  File "/usr/lib/python2.7/lib2to3/refactor.py", line 341, in refactor_file
    input, encoding = self._read_python_source(filename)
  File "/usr/lib/python2.7/lib2to3/refactor.py", line 337, in _read_python_source
    return _from_system_newlines(f.read()), encoding
  File "/usr/lib/python2.7/codecs.py", line 688, in read
    return self.reader.read(size)
  File "/usr/lib/python2.7/codecs.py", line 494, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 40: invalid continuation byte
**** /3/9 - "/bin/addr2line"
>> /???/?????????
/bin/addr2line: 'a.out': No such file
**** /3/10 - "/bin/aa-enabled"
>> /???/??????????
unknown or incompatible options
/bin/aa-enabled: [options]
  options:
  -x | --exclusive    Shared interfaces must be available
  -q | --quiet        Don't print out any messages
  -h | --help         Print help
**** cftp3

/bin/cftp3
/???/????3

>> /???/????3 /???/??????_????/??????32 /???/??????_????/??????31 /???/??????_????/??????30

/usr/lib/python3/dist-packages/twisted/conch/ssh/transport.py:97: CryptographyDeprecationWarning: Blowfish has been deprecated
  b"blowfish-cbc": (algorithms.Blowfish, 16, modes.CBC),
/usr/lib/python3/dist-packages/twisted/conch/ssh/transport.py:101: CryptographyDeprecationWarning: CAST5 has been deprecated
  b"cast128-cbc": (algorithms.CAST5, 16, modes.CBC),
/usr/lib/python3/dist-packages/twisted/conch/ssh/transport.py:106: CryptographyDeprecationWarning: Blowfish has been deprecated
  b"blowfish-ctr": (algorithms.Blowfish, 16, modes.CTR),
/usr/lib/python3/dist-packages/twisted/conch/ssh/transport.py:107: CryptographyDeprecationWarning: CAST5 has been deprecated
  b"cast128-ctr": (algorithms.CAST5, 16, modes.CTR),
Traceback (most recent call last):
  File "/bin/cftp3", line 33, in <module>
    sys.exit(load_entry_point('Twisted==22.1.0', 'console_scripts', 'cftp')())
  File "/bin/cftp3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/twisted/conch/scripts/cftp.py", line 20, in <module>
    from twisted.conch.client import connect, default, options
  File "/usr/lib/python3/dist-packages/twisted/conch/client/connect.py", line 5, in <module>
    from twisted.conch.client import direct
  File "/usr/lib/python3/dist-packages/twisted/conch/client/direct.py", line 7, in <module>
    from twisted.internet import defer, protocol, reactor
  File "/usr/lib/python3/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/lib/python3/dist-packages/twisted/internet/default.py", line 55, in <module>
    install = _getInstallFunction(platform)
  File "/usr/lib/python3/dist-packages/twisted/internet/default.py", line 43, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/lib/python3/dist-packages/twisted/internet/epollreactor.py", line 19, in <module>
    from twisted.internet import posixbase
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 37, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import (
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
PermissionError: [Errno 13] Permission denied: '/var/crash/_usr_bin_cftp3.11033.crash'

Original exception was:
Traceback (most recent call last):
  File "/bin/cftp3", line 33, in <module>
    sys.exit(load_entry_point('Twisted==22.1.0', 'console_scripts', 'cftp')())
  File "/bin/cftp3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/twisted/conch/scripts/cftp.py", line 20, in <module>
    from twisted.conch.client import connect, default, options
  File "/usr/lib/python3/dist-packages/twisted/conch/client/connect.py", line 5, in <module>
    from twisted.conch.client import direct
  File "/usr/lib/python3/dist-packages/twisted/conch/client/direct.py", line 7, in <module>
    from twisted.internet import defer, protocol, reactor
  File "/usr/lib/python3/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/lib/python3/dist-packages/twisted/internet/default.py", line 55, in <module>
    install = _getInstallFunction(platform)
  File "/usr/lib/python3/dist-packages/twisted/internet/default.py", line 43, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/lib/python3/dist-packages/twisted/internet/epollreactor.py", line 19, in <module>
    from twisted.internet import posixbase
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 37, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python3/dist-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python3/dist-packages/twisted/protocols/tls.py", line 40, in <module>
    from OpenSSL.SSL import (
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
**** /???/*4*
>> /???/*4*
/bin/base64: extra operand ‘/bin/cpan5.34-x86_64-linux-gnu’
Try '/bin/base64 --help' for more information.
**** /4/?
>> /????/?
sh: 1: /????/?: not found
>> /????/??
sh: 1: /proc/fb: Permission denied
>> /????/???
sh: 1: /boot/efi: Permission denied
>> /????/????
sh: 1: /boot/grub: Permission denied
>> /????/?????
sh: 1: /proc/iomem: Permission denied
>> /????/??????
sh: 1: /home/ubuntu: Permission denied
>> /????/? ??? ???
sh: 1: /boot/vmlinuz: Permission denied
>> /????/????????
sh: 1: /home/bandit10: Permission denied
**** /3/3/?
>> /???/???/??
sh: 1: /dev/pts/10: Permission denied
>> /???/???/???
sh: 1: /dev/net/tun: Permission denied
>> /???/???/????
sh: 1: /dev/pts/ptmx: Permission denied
>> /???/???/?????
sh: 1: /etc/ssl/certs: Permission denied
>> /???/???/??????
sh: 1: /etc/gss/mech.d: Permission denied
>> /???/???/???????
sh: 1: /etc/gdb/gdbinit: Permission denied
>> /???/???/????????
sh: 1: /etc/apt/keyrings: Permission denied
** leviathan
- $ ssh -v -l leviathan2 -p 2223 leviathan.labs.overthewire.org
- PASSWORDS
  leviathan0 ---- 0
  PPIfmI1qsA ---- 1
  mEh5PNl10e ---- 2

* Exercism
- AWK
  - ME: In awk "pattern matching" is king.
        And strings and regular expressions are at the center of it all.
- "scrable score"
  - AWK's switch has support for regular expressions
- "grade school"
  - some community solutions didn't work for me as they won't sorting twice grade/name
  - it worked on their platform though
- "bob" - wacky regular expressions
  - [^a-z] matches a character that isn't a-z
  - [?] matches the "?" character
  - \s matches a space character
  - RS="^$", read the whole input as a single record
